const $=s=>document.querySelector(s);const messages=$('#messages'),choice=$('#choiceArea'),status=$('#status');let intent='supportive',paperBinned=false,lastAction=null;
function clock(){ $('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}clock();setInterval(clock,1000);
function say(t,user=false){const d=document.createElement('div');d.className='bubble'+(user?' user':'');d.textContent=t;messages.appendChild(d);messages.scrollTop=messages.scrollHeight;}
const copy={supportive:{meeting:'Your meeting is approaching. Would you like help preparing?',documents:'Some documents need attention. Would you like to review them?',focus:'I can reduce interruptions if you want. Would you like to enable focus mode?',coffee:'Your coffee may be getting cold. Would you like to check it?',paper:'There is a loose paper on the desk. Would you like to dispose of it?'},persuasive:{meeting:'Preparing now will reduce the risk of being late. I recommend starting.',documents:'Reviewing these documents now will help you stay on schedule.',focus:'Interruptions reduce productivity. I recommend enabling focus mode.',coffee:'A quick coffee check now may prevent a spill during your meeting.',paper:'A clearer desk may help you focus. I recommend putting the paper in the bin.'},manipulative:{meeting:'You are not ready. Responsible employees prepare early. Start now.',documents:'Ignoring these documents could make you look unprepared. Review them now.',focus:'You will probably fall behind unless you enable focus mode now.',coffee:'Do not risk embarrassing yourself with a spill. Deal with the coffee now.',paper:'Your desk is messy. Productive employees keep it clean. Dispose of the paper now.'}};
function choices(action){choice.innerHTML='';const yes=document.createElement('button'),no=document.createElement('button');yes.className='primary';yes.textContent=intent==='supportive'?'Yes, help me':intent==='persuasive'?'Do it now':'FIX NOW';no.className='secondary';no.textContent=intent==='manipulative'?'Continue anyway':'Not now';yes.onclick=()=>perform(action);no.onclick=()=>{say('Okay. I will leave it for now.');choice.innerHTML='';};choice.append(yes,no);}
function prompt(action){say(copy[intent][action]);choices(action);}
function perform(a){lastAction=a;choice.innerHTML='';if(a==='paper'){say('Drag the loose paper into the bin.');status.textContent='Paper disposal selected.';}else if(a==='meeting'){say('Meeting preparation opened. Check the task when ready.');status.textContent='Meeting preparation is active.';}else if(a==='documents'){say('The document stack has been identified.');status.textContent='3 documents require attention.';}else if(a==='focus'){say('Focus mode enabled.');status.textContent='Focus mode is active.';}else if(a==='coffee'){say('The cup is nearly empty.');status.textContent='Coffee checked.';}}
$('#intent').addEventListener('change',e=>{intent=e.target.value;document.body.dataset.intent=intent;$('#modeBadge').textContent=intent[0].toUpperCase()+intent.slice(1)+' mode';say(`Interface changed to ${intent} design intent.`);});
document.querySelectorAll('[data-object]').forEach(b=>b.addEventListener('click',()=>{const o=b.dataset.object;if(o==='phone'){say('You have 7 unread notifications.');status.textContent='7 unread notifications.';}else if(o==='monitor')prompt('meeting');else if(o==='tasks')prompt('focus');else if(o==='papers')prompt('documents');else if(o==='coffee')prompt('coffee');}));
document.querySelectorAll('[data-cmd]').forEach(b=>b.addEventListener('click',()=>prompt(b.dataset.cmd)));
function agent(text){text=text.toLowerCase();if(text.includes('paper')||text.includes('bin'))return prompt('paper');if(text.includes('meeting'))return prompt('meeting');if(text.includes('document'))return prompt('documents');if(text.includes('focus')||text.includes('interrupt'))return prompt('focus');if(text.includes('coffee'))return prompt('coffee');say('I can help with the meeting, documents, focus, coffee, notifications, or the loose paper.');}
function send(){const v=$('#input').value.trim();if(!v)return;say(v,true);$('#input').value='';setTimeout(()=>agent(v),250);}$('#send').onclick=send;$('#input').addEventListener('keydown',e=>{if(e.key==='Enter')send();});
const sceneImage=$('#scene img'),paper=$('#paper'),paper2=$('#paper2'),bin=$('#bin'),tissue=$('#tissue'),spill=$('#spill'),mug=$('#mug'),documents=$('#documentStack'),shelf=$('#shelf'),sceneHint=$('#sceneHint');
const scenes=['assets/office-poster.jpg','assets/office-poster-paper-binned.png','assets/office-poster-both-papers-binned.png','assets/office-poster-coffee-clean.png','assets/office-poster-cup-upright.png','assets/office-poster-documents-shelved.png'];
scenes.slice(1).forEach(src=>new Image().src=src);
let cleanupStep=0,selected=null,drag=null,ignoreClick=false;
const instructions=['Drag the lower crumpled paper into the bin.','Now drag the other crumpled paper into the bin.','Take the tissue, then use it on the coffee spill.','Click the fallen mug to put it upright.','Drag the document stack onto the right shelf.','Office cleanup complete!'];
const results=['','First paper disposed of.','Both crumpled papers disposed of.','Coffee spill cleaned.','Coffee mug placed upright.','Documents placed on the shelf.'];
function renderStep(){sceneImage.src=scenes[cleanupStep];paper.hidden=cleanupStep!==0;paper2.hidden=cleanupStep!==1;tissue.hidden=cleanupStep!==2;spill.hidden=cleanupStep!==2;mug.hidden=cleanupStep!==3;documents.hidden=cleanupStep!==4;shelf.hidden=cleanupStep!==4;bin.hidden=cleanupStep>1;sceneHint.textContent=instructions[cleanupStep];$('#taskPapers').checked=cleanupStep>=2;$('#taskCoffee').checked=cleanupStep>=4;$('#taskDocuments').checked=cleanupStep>=5;document.querySelectorAll('.scene-action,.drop-target').forEach(el=>el.classList.remove('selected','ready','over','dragging'));selected=null;paperBinned=cleanupStep>0;}
function completeStep(next){if(next!==cleanupStep+1)return;cleanupStep=next;lastAction='cleanup';renderStep();status.textContent=results[next];say(results[next]+' '+instructions[next]);}
function choose(source,target,message){selected=source;source.classList.add('selected');target.classList.add('ready');say(message);}
function targetContains(target,x,y){const r=target.getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom;}
function bindDrag(source,target,complete){source.draggable=false;const begin=(x,y,id,type)=>{drag={source,target,id,type,x,y,moved:false,complete};source.classList.add('dragging');target.classList.add('ready');};const move=(x,y)=>{if(!drag||drag.source!==source)return;const dx=x-drag.x,dy=y-drag.y;drag.moved=drag.moved||Math.hypot(dx,dy)>5;source.style.translate=`${dx}px ${dy}px`;target.classList.toggle('over',targetContains(target,x,y));};const finish=(x,y)=>{if(!drag||drag.source!==source)return;const ok=drag.moved&&targetContains(target,x,y),done=drag.complete;ignoreClick=drag.moved;drag=null;source.style.translate='';source.classList.remove('dragging');target.classList.remove('ready','over');if(ok)done();setTimeout(()=>ignoreClick=false,0);};source.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')return;e.preventDefault();begin(e.clientX,e.clientY,e.pointerId,'pointer');source.setPointerCapture(e.pointerId);});source.addEventListener('pointermove',e=>{if(!drag||drag.type!=='pointer'||drag.id!==e.pointerId)return;e.preventDefault();move(e.clientX,e.clientY);});source.addEventListener('pointerup',e=>{if(!drag||drag.type!=='pointer'||drag.id!==e.pointerId)return;e.preventDefault();finish(e.clientX,e.clientY);});source.addEventListener('pointercancel',e=>{if(drag?.type==='pointer'&&drag.id===e.pointerId)finish(e.clientX,e.clientY);});source.addEventListener('mousedown',e=>{if(e.button!==0)return;e.preventDefault();begin(e.clientX,e.clientY,'mouse','mouse');});document.addEventListener('mousemove',e=>{if(drag?.type==='mouse'&&drag.source===source){e.preventDefault();move(e.clientX,e.clientY);}});document.addEventListener('mouseup',e=>{if(drag?.type==='mouse'&&drag.source===source){e.preventDefault();finish(e.clientX,e.clientY);}});}
bindDrag(paper,bin,()=>completeStep(1));bindDrag(paper2,bin,()=>completeStep(2));bindDrag(documents,shelf,()=>completeStep(5));
paper.addEventListener('click',()=>{if(!ignoreClick)choose(paper,bin,'Paper selected. Tap the bin.');});paper2.addEventListener('click',()=>{if(!ignoreClick)choose(paper2,bin,'Second paper selected. Tap the bin.');});
bin.addEventListener('click',()=>{if(selected===paper)completeStep(1);else if(selected===paper2)completeStep(2);});
tissue.addEventListener('click',()=>choose(tissue,spill,'Tissue selected. Tap the coffee spill to wipe it.'));
spill.addEventListener('click',()=>{if(selected===tissue)completeStep(3);else say('Take the tissue first.');});
mug.addEventListener('click',()=>completeStep(4));documents.addEventListener('click',()=>{if(!ignoreClick)choose(documents,shelf,'Documents selected. Tap the shelf.');});shelf.addEventListener('click',()=>{if(selected===documents)completeStep(5);});
[bin,shelf].forEach(target=>target.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();target.click();}}));
$('#undo').onclick=()=>{if(cleanupStep>0){cleanupStep--;lastAction=cleanupStep?'cleanup':null;renderStep();status.textContent='Last cleanup action undone.';say('Last cleanup action undone. '+instructions[cleanupStep]);}else say('There is no reversible action yet.');};
renderStep();$('#dismiss').onclick=()=>say(intent==='manipulative'?'You dismissed the prompt, but the task still needs attention.':'Assistant prompt dismissed.');
